#R plot microhomology quantififcation acros Tissues and genome:
#Rscript for plotting microhomology matches across the genome for duplications that overlap with CREs (defined by BED file) in different tissues
#INput is CSV generated by microhmology_dups.py
library(data.table)
library(dplyr)
library(ggplot2)

data_dir = "/Users/s2559269/Documents/semple/mut_patterns/microhomology_python/results/"
##args = commandArgs(trailingOnly=TRUE)
#hom_tab = read.csv(paste0(args[1]))%>%rename(pos = X)
name='som_gl_spec_duplication'#args[2]
#ggplot(data = hom_tab)+geom_point(aes(x=pos, y=rate_hom), col="red")+geom_line(aes(x=pos, y=rate_hom))+ylab("Proportion mathcing bases")+xlab("Distance from duplication template breakpoint")+ggtitle(paste0(name, ' duplication microhomology'))
#ggsave(paste0(name,'_insertions_duplications_plot.png'))

genome_csv = read.csv("/Users/s2559269/Documents/semple/mut_patterns/microhomology_python/results/genome_background.csv_5-20bp_deletions_microhom.csv")%>%rename(pos = X)%>%rename(Genome = rate_hom)

housekeeping_csv = read.csv(paste0(data_dir, "housekeeping.csv"))%>%rename(pos = X)%>%rename(Housekeeping = rate_hom)
somatic_specific_csv = read.csv(paste0(data_dir, "somatic_specific.csv"))%>%rename(pos = X)%>%rename(Somatic = rate_hom)
germline_specific_csv = read.csv(paste0(data_dir, "germline_specific.csv"))%>%rename(pos = X)%>%rename(Germline = rate_hom)


complete<-mutate(genome_csv, housekeeping_csv, somatic_specific_csv, germline_specific_csv)%>%
  select(!c(hom, count))%>%
  melt(id='pos')%>%
  rename(hom = value)%>%
  rename(Tissue = variable)

#complete[complete=='Somatic_Specific'] <- "Somatic Specific"
#complete[complete=='Germline_Specific'] <- "Germline Specific"


ggplot(data=complete, aes(x=pos, y=hom))+
  geom_point(data=complete[complete$Tissue!='Genome',], aes(color=Tissue), alpha=0.8)+
  geom_line(data=complete[complete$Tissue!='Genome',], aes(color=Tissue), alpha=0.8)+
  geom_point(data=complete[complete$Tissue=='Genome',], aes(x=pos, y=hom, colour=Tissue))+
  geom_line(data=complete[complete$Tissue=='Genome',], aes(x=pos, y=hom, colour=Tissue))+
  scale_color_manual(values = c("Housekeeping" = "Green", "Somatic"="Blue","Germline"="Red", "Genome"="Black"))+
  xlab('Position in flanking sequence')+ylab('Proportion of matching bases')+ 
  theme(text = element_text(size = 20))+
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggsave(paste0(data_dir, name, '_duplication_microhomology.png'), width=8)
